### ISSUE TITLE
Module No Longer Reports Emulated Profiles

### ISSUE THREAD

**Issue by miawri** [munkireport/profile#16]
Emulated profile information is no longer gathered in profiles.py even though the MCX is present in local MCX.

I'm not sure when this started happening but I imagine it was after the MR 5.8 / python3 upgrade.

**Comment by tuxudo** [comment]
Are you able to share one of the MCX profiles that isn't showing up in MunkiReport?

**Comment by tuxudo** [comment]
This is fixed with version v4.1 of the module
