### ISSUE TITLE
Fatal error when clicking links in Profile Report page

### ISSUE THREAD

**Issue by arekdist** [munkireport/profile#8]
At Profile Report page, when clicking any link (e.g. to com.apple.mdm payload) I'm getting following error page:

`
Fatal error: Uncaught TypeError: Argument 1 passed to Illuminate\Database\Eloquent\Model::__construct() must be of the type array, string given, called in /usr/share/nginx/html/munkireport-4.3.2/vendor/munkireport/profile/profile_controller.php on line 71 and defined in /usr/share/nginx/html/munkireport-4.3.2/vendor/illuminate/database/Eloquent/Model.php:146 Stack trace: #0 /usr/share/nginx/html/munkireport-4.3.2/vendor/munkireport/profile/profile_controller.php(71): Illuminate\Database\Eloquent\Model->__construct('FVFX11LXHV2F') #1 [internal function]: Profile_controller->items('Remote Manageme...', 'com.apple.mdm') #2 /usr/share/nginx/html/munkireport-4.3.2/app/controllers/module.php(81): call_user_func_array(Array, Array) #3 /usr/share/nginx/html/munkireport-4.3.2/system/kissmvc_core.php(88): munkireport\controller\Module->load('profile', 'items', 'Remote%20Manage...', 'com.apple.mdm') #4 /usr/share/nginx/html/munkireport-4.3.2/system/kissmvc.php(17): KISS_Engine->__construct(Array, 'show', 'index', 'AUTO') #5 /usr/sha in /usr/share/nginx/html/munkireport-4.3.2/vendor/illuminate/database/Eloquent/Model.php on line 146
`

**Comment by tuxudo** [comment]
This is fixed in v3.1 of the module.
