### ISSUE TITLE
SQL error when submitting profile data

### ISSUE THREAD

**Issue by flammable** [munkireport/profile#9]
I updated to 5.6.2 today, and I'm seeing this in the logs for MunkiReport:

```
Server An error occurred while processing: \Profile_model
Server Error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'payload_data' at row 1
```

Since it's ingesting the contents of each profile, I'm guessing one of the profiles has too much data? If there's a good way of narrowing it down, I can provide the offending profile. Thanks!

**Comment by tuxudo** [comment]
This is fixed in v3.1 of the module
